### ISSUE TITLE
Could not start storage pool: cannot open directory '/vm-disks': No such file or directory

### ISSUE THREAD

**Issue by NL-TCH** [hoeghh/rancher-launcher-kvm#3]
**### i got the following error:(running on ubuntu 18.04 clean install with KVM preinstalled)**
sudo ./provision.sh 4 
Public key not found. It will be left black...
Creating 4 of servers...
Creating VM 1
Creating VM 2
Using port 5901
Cleaning up old kickstart file...
Creating VM 3
Creating VM 4
Creating new ks.cfg file...
Using port 5902
Cleaning up old kickstart file...
Using port 5903
Cleaning up old kickstart file...
Using port 5904
Cleaning up old kickstart file...
Creating new ks.cfg file...
Creating new ks.cfg file...
Creating new ks.cfg file...
Creating disc image...
Formatting '/vm-disks/k8s-1.qcow2', fmt=qcow2 size=53687091200 cluster_size=65536 lazy_refcounts=off refcount_bits=16
qemu-img: /vm-disks/k8s-1.qcow2: Could not create file: No such file or directory
Creating virtual machine and running installer...
Creating disc image...
Creating disc image...
Creating disc image...
Formatting '/vm-disks/k8s-2.qcow2', fmt=qcow2 size=53687091200 cluster_size=65536 lazy_refcounts=off refcount_bits=16
Formatting '/vm-disks/k8s-4.qcow2', fmt=qcow2 size=53687091200 cluster_size=65536 lazy_refcounts=off refcount_bits=16
qemu-img: /vm-disks/k8s-4.qcow2: Could not create file: No such file or directory
Formatting '/vm-disks/k8s-3.qcow2', fmt=qcow2 size=53687091200 cluster_size=65536 lazy_refcounts=off refcount_bits=16
**qemu-img: /vm-disks/k8s-3.qcow2: Could not create file: No such file or directory**
Creating virtual machine and running installer...
Creating virtual machine and running installer...
qemu-img: /vm-disks/k8s-2.qcow2: Could not create file: No such file or directory
Creating virtual machine and running installer...
**ERROR    Error: --disk path=/vm-disks/k8s-1.qcow2,size=15: Could not start storage pool: cannot open directory '/vm-disks': No such file or directory
ERROR    Error: --disk path=/vm-disks/k8s-2.qcow2,size=15: Could not start storage pool: cannot open directory '/vm-disks': No such file or directory
ERROR    Error: --disk path=/vm-disks/k8s-3.qcow2,size=15: Could not start storage pool: cannot open directory '/vm-disks': No such file or directory
ERROR    Error: --disk path=/vm-disks/k8s-4.qcow2,size=15: Could not start storage pool: cannot open directory '/vm-disks': No such file or directory**
Add these entries to your hosts /etc/hosts

192.168.122.111 k8s-1
192.168.122.112 k8s-2
192.168.122.113 k8s-3
192.168.122.114 k8s-4

**Comment by NL-TCH** [comment]
installed KVM with the following tutorial: 
https://linuxize.com/post/how-to-install-kvm-on-ubuntu-18-04/

**Comment by hoeghh** [comment]
Did you create directories needed?

You get this error
/vm-disks/k8s-1.qcow2: Could not create file: No such file or directory

Either create this folder or change the location in the config file.

**Comment by hoeghh** [comment]
Closing this old issue...
