### ISSUE TITLE
Please update to Helm v3 and modern cert-manager

### ISSUE THREAD

**Issue by oskapt** [hoeghh/rancher-launcher-kvm#4]
Hi! I'm the host of [Coffee and Cloud Native](https://cncn.io) and the Director of Community and Evangelism for Rancher Labs (now SUSE). I came across your project today and considered putting it on the show. I like that it's available for KVM - we're seeing a lot of work for KVM/QEMU, and having Rancher available in those environments is great! 

I noticed, though, that your Rancher install script is using Helm v2 with (insecure) Tiller, and it's not using the latest cert-manager instructions (including `--installCRDs=true`), so it's not going to work.

If you would be so kind as to update to the latest installation docs, that would be fantastic!

**Comment by oskapt** [comment]
I'm going to put it on the show anyway and ask the Community to lend a hand.

**Comment by hoeghh** [comment]
Hi @oskapt 

Thanks a lot. If nobody sends a pull request, i will try and get it up to date myself.
And thank you so much for the exposure on the show.

**Comment by hoeghh** [comment]
This has been resolved by @kha7iq in #5 
Thanks for the help. Much appreciated.
